services:
  - type: web
    name: lugarerrado-searxng-vladicho
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./searxng/Dockerfile
    dockerContext: ./searxng
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: SEARXNG_SECRET
        generateValue: true
      - key: SEARXNG_BASE_URL
        value: https://lugarerrado-searxng-vladicho.onrender.com/
      - key: SEARXNG_PORT
        value: "8080"
      - key: SEARXNG_BIND_ADDRESS
        value: "0.0.0.0"
