/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4e7e8feeeefc41c6201b99ecb888b90b)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SEARCH_BACKEND: "https://lugarerrado-searxng-vladicho.onrender.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEARCH_BACKEND">> {}
}
