use_default_settings:
  engines:
    keep_only:
      - bing
      - wikipedia

general:
  instance_name: Lugar Errado Search
  enable_metrics: false

search:
  safe_search: 1
  autocomplete: ""
  default_lang: pt-BR
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  public_instance: false
  image_proxy: false
